#!/bin/sh
######################################
# tagr install script
######################################


if [ -d "$PWD/dtags" ]
then
  ln -fs "$PWD/dtags" /usr/local/bin
fi

if ! [ -d "~/.dtags" ]
then
  ln -fs '~/.dtags/dtags' /usr/local/bin
fi

chmod 755 /usr/local/bin/dtags

dtags init
