#!/bin/sh

# dtags install script
######################################
echo 'starting installation'
if [ -f ~/.dtags/dtags ]; then
  echo 'github install'
  ln -fs '~/.dtags/dtags' /usr/local/bin
elif [ -f "$PWD/dtags" ]; then
  echo 'manual install'
  ln -fs "$PWD/dtags" /usr/local/bin
else
  echo 'error during installation, please check documentation'
fi

chmod 755 /usr/local/bin/dtags

dtags init
